### ISSUE TITLE
external dependency on downloads.mysql.com

### ISSUE THREAD

**Issue by brcarp** [customink/mysql2-lambda#2]
If `https://downloads.mysql.com/archives/` goes away, the `curl` in the `Dockerfile` will fail, presenting a rather critical external dependency. Is this at all a concern?

**Comment by metaskills** [comment]
I'd imagine the fix would be to use another download location. Do you think there is a more stable choice to warrant changing?

**Comment by metaskills** [comment]
Closing this out. I would like to consider this project deprecated when using Lambda Containers. I recently did an example on how to split dev/build dependences and runtime dependencies (sorta, they are already included in official Ruby base images with Debian) and would rather see folks move off Amazon Linux 2 Lambda containers which maxes out to Ruby 2.7. Details here.

https://github.com/customink/lamby-cookiecutter/pull/21
