### ISSUE TITLE
require: 'mysql2' is NOT working in bundler

### ISSUE THREAD

**Issue by nnat425** [customink/mysql2-lambda#6]
Receiving the following error in my files when executing or running tests:

`cannot load such file -- mysql2/mysql2`.

**Comment by nnat425** [comment]
Why was this closed?

**Comment by metaskills** [comment]
Sorry, I made comments in other issues and I should have shared here. Given Lambda Containers are a thing now... and coupled with the fact that there are no AWS provided Amazon Linux 2 / Lambda containers higher than Ruby 2.7, I'd like to consider this project deprecated in favor of using custom images with the RIC installed. This is really easy to do and I outlined it here for those curious. https://github.com/customink/lamby-cookiecutter/pull/21

Is that more helpful?

**Comment by nnat425** [comment]
Yes! Thank you!
